name: Build & Release

on:
  push:
    tags:
      - "v*.*.*" # e.g., v1.0.0

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables for Electron
        run: |
          echo "REACT_APP_API_BASE_URL=https://hr-api-3005.go9.me" >> $GITHUB_ENV
          echo "REACT_APP_BUILD_TARGET=production" >> $GITHUB_ENV

      - name: Build Electron App
        run: npm electron-build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_ENV: production
