name: Build & Release

on:
  push:
    tags:
      - "v*.*.*" # e.g., v1.0.0

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Electron App
        run: |
          echo "VITE_BUILD_TARGET=electron" >> $GITHUB_ENV
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_ENV: production
