name: Test Build

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test-build:
    if: github.event.head_commit.message != 'Trigger deploy main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Test build process
        run: |
          echo "Testing build process..."
          echo "BUILD_TARGET: $BUILD_TARGET"
          echo "VITE_API_URL: $VITE_API_URL"
          npm run build
        env:
          BUILD_TARGET: electron
          VITE_API_URL: https://hr-api-3005.go9.me

      - name: Check build output
        run: |
          echo "Checking build output..."
          if [ -f "dist/index.html" ]; then
            echo "✅ index.html exists"
          else
            echo "❌ index.html not found"
            exit 1
          fi
          
          if [ -d "dist/assets" ]; then
            echo "✅ assets directory exists"
            ls -la dist/assets/
          else
            echo "❌ assets directory not found"
            exit 1
          fi
        shell: bash
